apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tp-link-hs110-bigquery-exporter.fullname" . }}
  labels:
    {{- include "tp-link-hs110-bigquery-exporter.labels" . | nindent 4 }}
data:
  bq-project-id: {{ .Values.config.bqProjectID | quote }}
  bq-dataset: {{ .Values.config.bqDataset | quote }}
  bq-table: {{ .Values.config.bqTable | quote }}  
  timeout-seconds: {{ .Values.config.timeoutSeconds | quote }}
  interval-seconds: {{ .Values.config.intervalSeconds | quote }}